# -*- encoding: utf-8 -*-
require File.expand_path('../lib/character/version', __FILE__)

Gem::Specification.new do |gem|
  gem.name          = 'character'
  gem.version       = Character::VERSION
  gem.summary       = 'Data management framework'
  gem.description   = ''
  gem.license       = ''

  gem.authors       = ['Alexander Kravets', 'Roman Lupiichuk', 'Maksym Melnyk']
  gem.email         = 'alex@slatestudio.com'
  gem.homepage      = 'https://github.com/slate-studio/character'

  gem.require_paths = ['lib']
  gem.files         = `git ls-files`.split($\)
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})

  # Supress the warning about no rubyforge project
  gem.rubyforge_project = 'nowarning'

  # javascripts & stylesheets
  gem.add_runtime_dependency 'jquery-ui-rails'
  gem.add_runtime_dependency 'underscore-rails'
  gem.add_runtime_dependency 'marionette-rails'
  gem.add_runtime_dependency 'eco'
  gem.add_runtime_dependency 'compass-rails'
  gem.add_runtime_dependency 'foundation-rails'
  gem.add_runtime_dependency 'font-awesome-rails'
  gem.add_runtime_dependency 'momentjs-rails'

  # auth method
  gem.add_runtime_dependency 'browserid-auth-rails'

  # forms are autogenerated for editable mongoid models
  gem.add_runtime_dependency 'simple_form'
  gem.add_runtime_dependency 'nested_form'

  # index action pagination feature is implemented
  # using kaminari library
  # TODO: check if we need this
  gem.add_runtime_dependency 'kaminari'

  # Test dependencies
  gem.add_development_dependency 'mongoid', '~> 3.0.0'
  gem.add_development_dependency 'rspec-rails'
  gem.add_development_dependency 'database_cleaner'
  gem.add_development_dependency 'factory_girl_rails', '~> 4.0'
end